name: Master Run

on:
  workflow_dispatch:

jobs:
  fetch_uuids:
    uses: ./.github/workflows/fetch_uploadcare_uuids.yml

  process_images:
    needs: fetch_uuids
    uses: ./.github/workflows/process_images.yml